name: m3u_germany_tv
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  http: ^0.13.5
  m3u_nullsafe: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
