name: german_tv_m3u
description: public german tv channels
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.5
  m3u_nullsafe: ^1.0.4

dev_dependencies:
  lints: ^2.0.0