name: Build Docker

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker container
        run: docker build --tag ghcr.io/josxha/german-tv-m3u .
      - name: Push Docker container
        run: docker push ghcr.io/josxha/german-tv-m3u